export enum RESULT_ROLL_TYPE {
  DIAMOND = 'DIAMOND',
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  BRONZE = 'BRONZE',
  NOTHING = 'NOTHING',
}

export enum PRIZE_VIEW_OPEN_FROM {
  INIT,
  BAG,
  REFENING,
}

export enum SORT_TYPE {
  UP_TO,
  DOWN_TO,
}

export enum MERGE_STATUS {
  INITITAL = 'MERGE_STATUS__INITITAL',
  PREPARE = 'MERGE_STATUS__PREPARE',
  MERGING = 'MERGE_STATUS__MERGING',
  MERGE_SUCCESS = 'MERGE_STATUS__MERGE_SUCCESS',
  MERGE_FAILED = 'MERGE_STATUS__MERGE_FAILED',
}

export enum SELL_PRIZE_OPTION {
  ONE,
  ALL,
  CUSTOM,
}

export enum META_TYPE {
  CUT,
  SELL,
}

export enum META_STATUS {
  INITITAL,
  PREPARE,
  OPEN_MODAL,
}
