export enum ROLL_TYPE {
  DIAMOND = 'DIAMOND',
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  BRONZE = 'BRONZE',
  CUSTOM = 'CUSTOM',
}

export enum RESULT_ROLL_TYPE {
  DIAMOND = 'DIAMOND',
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  BRONZE = 'BRONZE',
  NOTHING = 'NOTHING',
}

export enum PRIZE_VIEW_OPEN_FROM {
  INIT,
  BAG,
  REFENING,
}

export enum ICONS {
  GEMCHAIN = 'GEMCHAIN',
  TRAIBALPENDANT = 'TRAIBALPENDANT',
  OYSTERPEARL = 'OYSTERPEARL',
  EMERALD = 'EMERALD',
  POWER_RING = 'POWER_RING',
}

export enum SORT_TYPE {
  UP_TO,
  DOWN_TO,
}

export enum MERGE_STATUS {
  INITITAL,
  PREPARE,
  MERGING,
  MERGE_SUCCESS,
  MERGE_FAILED,
}
