export enum ICONS {
  // Ring & Jewellery
  GEMCHAIN = 'GEMCHAIN',
  TRAIBALPENDANT = 'TRAIBALPENDANT',
  OYSTERPEARL = 'OYSTERPEARL',
  EMERALD = 'EMERALD',
  POWER_RING = 'POWER_RING',
  DIAMOND_HILT = 'DIAMOND_HILT',
  CROWN = 'CROWN',
  JEWELED_CHALICE = 'JEWELED_CHALICE',
  HEART_NECKLACE = 'HEART_NECKLACE',
}
